#+TITLE:     org-webpage's README
#+AUTHOR:    Feng Shu
#+EMAIL:     tumashu@163.com
#+DATE:      2015-04-01


* Introduction

org-webpage is a static site generator based on [[http://orgmode.org/][org-mode]], which is a fork of Kelvin H's [[https://github.com/kelvinh/org-page][org-page]].

org-webpage provides similar features with org-page:

#+BEGIN_EXAMPLE
1) Org sources and html files managed by git
2) Incremental publication (according to =git diff= command)
3) Category support
4) Tags support (auto generated)
5) RSS support (auto generated)
6) Search engine support (auto generated)
7) A beautiful theme
8) Theme customization support
9) Commenting (implemented using disqus/duoshuo)
10) Website traffic analytics (implemented using google analytics)
11) Index/about page support (auto generated if no default is provided)
12) Highly customizable
#+END_EXAMPLE

The main differents of two projects are as follow:

1. org-page focus on personal blog while org-webpage is main used to
   generate small project website.
2. org-page use many customizable variables to configure org-page
   while org-website use an `org-publish-project-alist' style
   alist to adjust org-website's behaver.

   Managing multi-site configs in an emacs session with org-website is more
   simple than with org-page.
3. org-website can deal with "increment" or "inherit" themes.

   A "increment" theme is a mod theme which only include changed template,
   css and other files, the files same with base theme doesn't include.

   org-webpage autosearch the same files from base theme when use "increment"
   theme.
4. org-website include a tiny emacs web server, which can be used to test publish.
5. ...


** Workflow

1. Specify a git repo where the org source
   files will be on the "source" branch and the generated html files
   will be on the "master" branch (the branch names can be
   customized). Repos may be created manually or by
   org-webpage's =owp/new-repository= command.
2. Specify a "base commit" (the most recent prior commit will be used if
   omitted). org-webpage will read changes between the latest commit
   and the specified base commit on branch "source". The changes
   will then be marked for publication.
3. org-webpage does preparation jobs.
4. Publish the changes read in step 2. A change can be an addition,
   a modification, or a deletion.  *org-webpage is designed to handle all of*
   *these kinds of changes but since deletion does not happen often, *
   *org-webpage has not implemented it yet.*
5. Update the index page for each category and tag.
6. Publication finished.

* Usage

*Here is a general introduction about how to use org-webpage, for more detailed introduction and configuration, please see
"tips.org" in the "documents" folder.*

** Installation

org-webpage is now available from the famous emacs package repo [[http://melpa.milkbox.net/][melpa]]
so the recommended way is to install it through emacs' package
management system. For more info about installation, please see
*tips.org* in the "doc" folder.

** Configuration
The follow code is my website's config, you can adjust and paste it to your =.emacs= file:

#+BEGIN_SRC emacs-lisp :eval no
;; the following is only needed if you install org-page manually
(add-to-list 'load-path "path/to/org-webpage")

(require 'org-webpage)

(setq eh-website-op-config
      `("tumashu.github.com"
        :repository-directory "~/project/emacs-packages/tumashu.github.com"
        :site-domain "http://tumashu.github.com/"
        :site-main-title "Tumashu 的个人小站"
        :site-sub-title "(九天十地，太上忘情！！！)"
        :theme (worg)
        :personal-github-link "https://github.com/tumashu/tumashu.github.com"
        :personal-avatar "/media/img/horse.jpg"
        :personal-duoshuo-shortname "tumashu-website"
        :web-server-docroot "~/.emacs.d/org-webpage-server/tumashu.github.com"
        :web-server-port 7654))

(add-to-list 'owp/project-config-alist
             eh-website-op-config)
#+END_SRC

The below is a more complex example, which is use by chinese-pyim package:

#+BEGIN_SRC emacs-lisp :eval no
(defun pyim-path (&optional filename)
  (concat (file-name-directory
           (locate-library "chinese-pyim")) (or filename "")))

(setq pyim-website-org-webpage-config
      `("chinese-pyim"
        :repository-directory ,(pyim-path)
        :site-domain "http://tumashu.github.com/chinese-pyim"
        :site-main-title "Chinese-pyim"
        :site-sub-title "(一个 emacs 环境下的中文拼音输入法)"
        :repository-org-branch "master"
        :repository-html-branch "gh-pages"
        :default-category "documents"
        :theme (worg)
        :personal-github-link "https://github.com/tumashu/chinese-pyim"
        :personal-avatar "/media/img/horse.jpg"
        :personal-duoshuo-shortname "tumashu-website"
        :preparation-function pyim-preparation-org-files
        :addition-files-function owp/git-ignored-files
        :org-export-function pyim-org-export-function
        :web-server-docroot "~/.emacs.d/org-webpage-server/chinese-pyim"
        :web-server-port 9876
        ))

(add-to-list 'owp/project-config-alist
             pyim-website-org-webpage-config)

(defun pyim-devtools-generate-readme-and-index ()
  (interactive)
  (let* ((el-file (concat (f-parent (locate-library (symbol-name 'chinese-pyim)))
                          "/chinese-pyim.el"))
         (org-file (concat (file-name-sans-extension el-file) ".org")))
    (lentic-doc-orgify-if-necessary el-file)
    (if (file-exists-p org-file)
        (with-current-buffer (find-file-noselect org-file)
          (let ((org-export-filter-paragraph-functions '(pyim-devtools-org-clean-space))
                (org-export-select-tags '("README"))
                (indent-tabs-mode nil)
                (tab-width 4))
            (org-export-to-file 'gfm "README.md")
            (org-export-to-file 'org "index.org")))
      (message "Generate README fail!!!"))))

(defun pyim-org-export-function ()
  "A function with can export org file to html."
  (let ((org-export-filter-paragraph-functions
         '(pyim-devtools-org-clean-space))
        (org-export-select-tags '("README" "devel"))
        (indent-tabs-mode nil)
        (tab-width 4))
    (org-export-as 'html nil nil t nil)))

(defun pyim-preparation-org-files ()
  "Generate org files by lentic."
  (message "Generating org files by lentic ...")
  (lentic-doc-orgify-package 'chinese-pyim)
  (pyim-devtools-generate-readme-and-index))

#+END_SRC


You can find more config options and theirs default values by commands:

#+BEGIN_EXAMPLE
C-h v owp/project-config-alist
C-h v owp/config-fallback
#+END_EXAMPLE


** Publication
The simplest way is run:

#+BEGIN_EXAMPLE
M-x owp/do-publication
#+END_EXAMPLE

This command will ask you some questions:

1. Which project do you want to publish?
2. Publish all org files of "XXXXX" project?
3. Publish to:  [Yes] Web server docroot, [No] Original repo.
4. Auto commit to repo?
5. Auto push to remote repo?

You can use `owp/do-publication' in elisp, which let you code
your own quickly publication command:

#+BEGIN_SRC emacs-lisp
(owp/do-publication "project-name" nil "HEAD^1" "~/org-pub/" nil)
#+END_SRC

or:

#+BEGIN_SRC emacs-lisp
(call-interactively 'owp/do-publication)
#+END_SRC

* Dependencies

1. [[http://www.gnu.org/software/emacs/][emacs]]: this is an "of-course" dependency
2. [[http://orgmode.org/][org mode]]: v8.0 is required, please use =M-x org-version <RET>= to make sure you org mode version is not less than 8.0
3. [[http://git-scm.com][git]]: a free and open source version control system
4. [[https://github.com/Wilfred/mustache.el][mustache.el]]: a mustache templating library for Emacs
5. [[http://fly.srk.fer.hr/~hniksic/emacs/htmlize.el.cgi][htmlize.el]]: a library for syntax highlighting (usually this library is shipped with emacs)
6. [[https://github.com/magnars/dash.el][dash.el]]: a modern list library for Emacs
7. [[https://github.com/Wilfred/ht.el][ht.el]]: a modern hash-table library for Emacs
8. web-server: a web server library for Emacs

* Known issues

- Currently the deletion change handler has not been implemented so
  if you deleted some org sources, you may have to manually delete
  corresponding generated html files.
- URI path change detection is not available. That is, if you make a
  post with the URI "/blog/2013/03/25/the-old-post-name" and then
  change this value in your org source, org-webpage would be unable to
  detect that this has happened. it will only publish a new html
  file for you so you need to delete the old html file related to
  the old URI manually.
