#+TITLE:     org-webpage's README
#+AUTHOR:    Feng Shu
#+EMAIL:     tumashu@163.com
#+DATE:      2015-04-01


* Introduction

org-webpage is a static site generator based on [[http://orgmode.org/][org-mode]], which is a fork of Kelvin H's [[https://github.com/kelvinh/org-page][org-page]].

The main differents of two projects are as follow:

1. org-webpage's core don't hard code git.
2. org-webpage's default config is `org-publish-project-alist' style alist,
   which can manage multi-site configs in an emacs session easily.
3. org-website find theme-files from a *themes-list* in sequence and same theme-file
   first found will be used. User can set *fallback theme* with the help of this feature.
4. org-website include a tiny emacs web server, which can be used to test publish.
5. ...


* Workflow
TODO

* Usage
Here is a general introduction about how to use org-webpage, for more detailed introduction and configuration, please see
"tips.org" in the "documents" folder.*

** Installation

org-webpage is now available from the famous emacs package repo [[http://melpa.milkbox.net/][melpa]]
so the recommended way is to install it through emacs' package
management system. For more info about installation, please see
*tips.org* in the "doc" folder.

** Configuration
The follow code is [[http://tumashu.github.com][my website]]'s [[https://github.com/tumashu/tumashu.github.com/blob/source/eh-website.el][config]], you can adjust and paste it to your =.emacs= file:

#+BEGIN_SRC emacs-lisp
;; the following is only needed if you install org-page manually
(add-to-list 'load-path "path/to/org-webpage")

(require 'org-webpage)

(add-to-list 'owp/project-config-alist
             `("tumashu.github.com"
               :repository-directory "~/project/emacs-packages/tumashu.github.com"
               :site-domain "http://tumashu.github.com/"
               :site-main-title "Tumashu 的个人小站"
               :site-sub-title "(九天十地，太上忘情！！！)"
               :theme (worg)
               :source-browse-url ("Github" "https://github.com/tumashu/tumashu.github.com")
               :personal-avatar "/media/img/horse.jpg"
               :personal-duoshuo-shortname "tumashu-website"
               :web-server-docroot "~/.emacs.d/org-webpage-server/tumashu.github.com"
               :web-server-port 7654))
#+END_SRC

[[http://tumashu.github.io/chinese-pyim/][Chinese-pyim]] 's org-webpage [[https://github.com/tumashu/chinese-pyim/blob/master/chinese-pyim-devtools.el][config]] is a more complex example.

You can find more config options and theirs default values by commands:

#+BEGIN_EXAMPLE
C-h v owp/project-config-alist
C-h v owp/config-fallback
#+END_EXAMPLE

** Publication

#+BEGIN_EXAMPLE
M-x owp/do-publication
#+END_EXAMPLE

* Dependencies

1. [[http://www.gnu.org/software/emacs/][emacs]]: this is an "of-course" dependency
2. [[http://orgmode.org/][org mode]]: v8.0 is required, please use =M-x org-version <RET>= to make sure you org mode version is not less than 8.0
3. [[http://git-scm.com][git]]: a free and open source version control system
4. [[https://github.com/Wilfred/mustache.el][mustache.el]]: a mustache templating library for Emacs
5. [[http://fly.srk.fer.hr/~hniksic/emacs/htmlize.el.cgi][htmlize.el]]: a library for syntax highlighting (usually this library is shipped with emacs)
6. [[https://github.com/magnars/dash.el][dash.el]]: a modern list library for Emacs
7. [[https://github.com/Wilfred/ht.el][ht.el]]: a modern hash-table library for Emacs
8. [[https://github.com/eschulte/emacs-web-server][web-server]]: a web server library for Emacs

* Known issues

- Currently the deletion change handler has not been implemented so
  if you deleted some org sources, you may have to manually delete
  corresponding generated html files.
- URI path change detection is not available. That is, if you make a
  post with the URI "/blog/2013/03/25/the-old-post-name" and then
  change this value in your org source, org-webpage would be unable to
  detect that this has happened. it will only publish a new html
  file for you so you need to delete the old html file related to
  the old URI manually.
